CFLAGS = -Wall -std=c99
LDLIBS = -lm
CC = gcc

all: q1 q2 q3 q7 shell

q1:
	$(CC) $(CFLAGS) $(LDLIBS) -o q1 q1.c
q2:
	$(CC) $(CFLAGS) $(LDLIBS) -o q2 q2.c
q3:
	$(CC) $(CFLAGS) $(LDLIBS) -o q3 q3.c
q7:
	$(CC) $(CFLAGS) $(LDLIBS) -o q7 q7.c
shell:
	$(CC) $(CFLAGS) $(LDLIBS) -o shell shell.c
